### ISSUE TITLE
Doesn't declare dependencies

### ISSUE THREAD

**Issue by raxod502** [yewton/hugo.el#4]
In order for `hugo.el` to be compatible with `package.el` (and to be put on MELPA, and to be installed from EmacsMirror, …), a header of the following sort is required:

```
;; Package-Requires: ((f "0.19.0") (dash "2.13.0") (ht "2.2"))
```

I can provide a pull request if you want, but this should be a trivial addition.

**Comment by yewton** [comment]
@raxod502 Thank you very much for pointing out that and I'm sorry for not responding quite a long time 🙇 🙇 🙇 🙇
